management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web.exposure.include: '*'
  metrics:
    export.prometheus.enabled: true

spring:
  kafka:
    bootstrap-servers: http://localhost:29092
    properties:
      schema.registry.url: http://localhost:8085
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
